# Generated by Django 4.2.7 on 2023-12-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_studentmodel_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='date_time_field',
            field=models.DateTimeField(default='2023-11-11 12:30:30'),
        ),
    ]
