# Generated by Django 4.2.7 on 2023-12-05 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_studentmodel_date_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
