# Generated by Django 4.2.7 on 2023-12-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_studentmodel_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='float_field',
            field=models.FloatField(default=23.34),
        ),
    ]
