# Generated by Django 4.2.7 on 2023-12-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_studentmodel_integer_field_studentmodel_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='positive_big_integer_field',
            field=models.PositiveBigIntegerField(default=1234556576577),
        ),
    ]
