# Generated by Django 4.2.7 on 2023-12-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_studentmodel_positive_integer_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='slug_field',
            field=models.SlugField(default='fsdfds'),
        ),
    ]
