# Generated by Django 4.2.7 on 2023-12-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_studentmodel_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='small_integer_field',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='text_field',
            field=models.TextField(default='i love bangladesh'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='time_field',
            field=models.TimeField(default=' 11:11:11'),
        ),
    ]
