# Generated by Django 4.2.7 on 2023-12-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_studentmodel_small_integer_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='json_field',
        ),
    ]
